dev:
  build: .
  volumes:
    - .:/code

  working_dir: /code
  ports:
    - 5000:5000

  command: make

  links:
  - db

  environment:
    APP_ENV: dev
    DATABASE_URL: postgresql://postgres:mysecretpassword@db/
    FLASK_APP: application/app.py
    FLASK_DEBUG: 1

db:
  image: postgres:9.2
  ports:
  - 5432:5432
